GHA workflow for CPU unit testing
meta-pytorch/torchrec pull request #171
Opened 2022-03-24 10:20 UTC by KanchiShimono

Summary:
Adding GitHub Actions workflow for CPU unit testing triggered by each PR/merge.

2022-03-28 21:50 UTC, colin2328 commented
thanks @KanchiShimono  for starting this!

2022-04-04 21:03 UTC, colin2328 requested changes
@KanchiShimono putting it back to you, please combine the two phases since we dont need to separate

2022-04-04 21:03 UTC, colin2328 commented on .github/workflows/unittest_ci_cpu.yml
> +  build_on_cpu:
when running unit tests on GPUs, we separate the GHA steps into two phases:
1) build on CPU
2) test on GPU

since we are running it all on CPU, we don't need to do this. See https://github.com/pytorch/torchrec/blob/main/.github/workflows/release_build_cpu.yml#L12 for an example

2022-04-06 13:20 UTC, KanchiShimono commented on .github/workflows/unittest_ci_cpu.yml
> +  build_on_cpu:
@colin2328 
Thank you for your review!
I fixed to combine build and test phase.

2022-04-08 22:02 UTC, closed without merging