Add a DpProposer to enhance collective_plan execution speed
meta-pytorch/torchrec pull request #2286
Opened 2024-08-12 03:40 UTC by tiankongdeguiji

The collective_plan will encounter an NCCL timeout if the number of EmbeddingBagConfig exceeds 500, as noted in #2282 , To address this issue, we propose using a Proposer with dynamic programming to improve the execution speed of the collective plan.

In the case of `test_multiple_ebc_plan.py` mentioned in #2282, the collective plan with the DpProposer took only 11.86 seconds, whereas the original version took 904.90 seconds.

2024-08-12 04:37 UTC, tiankongdeguiji commented
Hi, @henrylhtsang  @IvanKobzarev  @joshuadeng  @PaulZhang12  can you review this?

2024-08-12 17:35 UTC, henrylhtsang commented
that sounds interesting, @sarckk do you want to take a look?

2024-08-15 00:29 UTC, sarckk requested changes
Hi @tiankongdeguiji thanks for this PR. I've been thinking about this for a while, but I don't fully understand how this DP is set up, and the purpose of multiple HBM bins. 

To my understanding, this proposer tries to explore the full space of possibilities (num_embedding_tables x num_sharding_variant x num_possible_partitions) assuming total HBM size is uniformly distributed across K equally-sized HBM bins. M * N * K represents the total search space of sharding type + partitioning these shards. Is this correct? If so, how do you tune the number of HBM bins per device? 

Could you provide some high-level description of the DP algorithm, as a docstring for this proposer? Thanks

2024-08-15 00:29 UTC, shinoss commented on torchrec/distributed/planner/proposers.py
> +            ]
nit 
```suggestion
        if not self._inited:
            return [
                sharding_options[0] for sharding_options in self._sharding_options_by_fqn.values()
            ]
```

2024-08-15 00:29 UTC, shinoss commented on torchrec/distributed/planner/planners.py
> +                DpProposer(),
Let's keep default proposers the same for backward compatibility

```suggestion
                GridSearchProposer(),
                GreedyProposer(),
                GreedyProposer(use_depth=False),
```

2024-08-15 00:29 UTC, shinoss commented on torchrec/distributed/planner/proposers.py
> +                            prev_perf, perv_hbm = dp[i - 1][nj][c]
```suggestion
                            prev_perf, prev_hbm = dp[i - 1][nj][c]
```

2024-08-15 00:29 UTC, shinoss commented on torchrec/distributed/planner/proposers.py
> +                                new_hbm = perv_hbm + hbm_by_fqn[i][j]
```suggestion
                                new_hbm = prev_hbm + hbm_by_fqn[i][j]
```

2024-08-15 00:29 UTC, shinoss commented on torchrec/distributed/planner/proposers.py
> +class DpProposer(Proposer):
nit: rename to `DynamicProgrammingProposer` as `Dp` in torchrec usually refers to Data Parallel

```suggestion
class DynamicProgrammingProposer(Proposer):
```

2024-08-15 00:29 UTC, shinoss commented on torchrec/distributed/planner/proposers.py
> +            bin_size = float(hbm_total) / K
let's be defensive and guard against `bin_size = 0` which will result in division by 0 in `_bytes_to_float_bin`

2024-08-15 12:58 UTC, tiankongdeguiji commented on torchrec/distributed/planner/planners.py
> +                DpProposer(),
In all of our test scenarios, the DynamicProgrammingProposer is faster than both the GreedyProposer and GridSearchProposer. Additionally, the performance of the sharding plans generated by the DynamicProgrammingProposer is better. Which scenario might encounter issues?

2024-08-15 13:09 UTC, tiankongdeguiji commented
> Hi @tiankongdeguiji thanks for this PR. I've been thinking about this for a while, but I don't fully understand how this DP is set up, and the purpose of multiple HBM bins.
> 
> To my understanding, this proposer tries to explore the full space of possibilities (num_embedding_tables x num_sharding_variant x num_possible_partitions) assuming total HBM size is uniformly distributed across K equally-sized HBM bins. M * N * K represents the total search space of sharding type + partitioning these shards. Is this correct? If so, how do you tune the number of HBM bins per device?
> 
> Could you provide some high-level description of the DP algorithm, as a docstring for this proposer? Thanks

I provide a high-level overview of the DP algorithm in docstring. 

The number of HBM bins affects both the plan counts and plan precision. We will generate plans with a total HBM constraint ranging from 0 to K in increments of the bin width, and keep the best perf plan in each bin. In most cases, we do not need to adjust the number of HBM bins per device, 100 bins is generally sufficient. However, if the number of tables becomes several thousand, we may need additional bins.

2024-08-16 06:59 UTC, tiankongdeguiji commented
In the `test_multiple_ebc_plan.py` case mentioned in #2282 , the collective plan with the DynamicProgrammingProposer has been further optimized to 1.48 seconds, while the first commit version of the DynamicProgrammingProposer took 11.86 seconds, and TorchRec now takes 904.90 seconds. @sarckk, could you take another look?

2024-08-20 17:31 UTC, closed without merging

2024-08-20 18:37 UTC, sarckk commented
@tiankongdeguiji thanks for the PR!