Fix EmbeddingEnumerator error raising
meta-pytorch/torchrec pull request #503
Opened 2022-07-06 06:48 UTC by zhuzilin

The old exception mechanism will raise error when Enumerator cannot find a compute kernel for given sharding type, which will disallow user to set only compute kernel constraints. For instance, user may hope to set the compute kernel as UVM, which leads to:

```python
constraints = {
    "table": ParameterConstraints(
        compute_kernels=[EmbeddingComputeKernel.FUSED_UVM_CACHING.value]
    )
}
```
However, the `data_parallel` does not allow UVM, which would stop the training. This PR is trying to fix this issue.

Thank you for your time on this PR :)

2022-07-06 16:56 UTC, joshuadeng requested changes
Thanks for the catch! Left some small follow up and it should be good to go

2022-07-06 16:56 UTC, joshuadeng commented on torchrec/distributed/planner/enumerators.py
> -            raise RuntimeError(
Instead of deleting this completely, let's make this `logger.warn`, and do the same in `_filter_sharding_types`, we don't want to raise 2 separate errors.

You can instantiate the logger with:
`import logging`
`logger: logging.Logger = logging.getLogger(__name__)`

2022-07-07 04:23 UTC, zhuzilin commented on torchrec/distributed/planner/enumerators.py
> -            raise RuntimeError(
fixed.

2022-07-07 04:33 UTC, joshuadeng approved these changes
Awesome, thanks!

2022-07-07 09:28 UTC, closed without merging