[tde] Migrate redis IO
meta-pytorch/torchrec pull request #805
Opened 2022-11-09 14:31 UTC by zhuzilin

This PR is migrating the redis IO plugin to the top level folder of torchrec. This plugin can be compiled with `BUILD_REDIS_IO` flag in cmake (`-DBUILD_REDIS_IO=ON`).

There are some issues we may need to discuss. 
- The PR introduced 2 external dependencies: [hiredis](https://github.com/redis/hiredis)(A minimal redis C client) and [lexy](https://github.com/foonathan/lexy)(A simple static typed C++ parser), the later one is used for parsing the URL like `192.168.3.1:3948/?db=3&&num_threads=2&&timeout=3s&&chunk_size=3000`. It will be great if we can find some lighter dependency for such usage.
- The PR introduced redis IO plugin as a shared library with [symbols needed for registering IO plugin](https://github.com/pytorch/torchrec/blob/712bbac3183cdfb25eca7c480099a2ee4be9c0f7/torchrec/csrc/dynamic_embedding/details/io_registry.cpp#L26-L54):
  ```bash
  $ nm -D torchrec/csrc/dynamic_embedding/details/redis/libredis_io.so | grep IO_
  000000000000cb30 T IO_Finalize
  0000000000028660 T IO_Initialize
  000000000000c7d0 T IO_Pull
  000000000000d020 T IO_Push
  000000000003f008 D IO_type
  ```
  This could serve as an example on how to create custom IO plugin. We could also register the redis plugin statically.

Thank you for your time on this long PR :)

gently ping @divchenko @colin2328 @reyoung

2022-11-14 15:15 UTC, divchenko requested changes
Lexy is a quite a heavy dependency indeed, let's try to use regex?

2022-11-14 15:15 UTC, divchenko commented on torchrec/csrc/dynamic_embedding/details/redis/url.h
> +  std::string username_;
here and everywhere else: these are public members, no need to add suffix "_"

2022-11-14 15:15 UTC, divchenko commented on torchrec/csrc/dynamic_embedding/details/redis/url.h
> +  std::optional<Auth> auth_;
confusing name, change to authority?

2022-11-14 15:15 UTC, divchenko commented on torchrec/csrc/dynamic_embedding/details/redis/url.h
> +struct Auth {
same as above - Authority

2022-11-14 15:15 UTC, divchenko commented on torchrec/csrc/dynamic_embedding/details/redis/url.h
> +struct ErrorCollector {
this should go away if we get rid of Lexy?

2022-11-14 15:15 UTC, divchenko commented on torchrec/csrc/dynamic_embedding/details/io_parameter.h
> +struct IOPullParameter {
Maybe "Fetch" is a better name (like in redis). Pull/push terminology comes from pub/sub so a bit confusing in this context.

2022-11-14 15:15 UTC, divchenko commented on torchrec/csrc/dynamic_embedding/details/io_parameter.h
> +      uint32_t data_len);
typedef this?

2022-11-15 09:35 UTC, zhuzilin commented on torchrec/csrc/dynamic_embedding/details/io_parameter.h
> +      uint32_t data_len);
fixed.

2022-11-15 09:35 UTC, zhuzilin commented on torchrec/csrc/dynamic_embedding/details/redis/url.h
> +  std::string username_;
fixed.

2022-11-15 09:35 UTC, zhuzilin commented on torchrec/csrc/dynamic_embedding/details/redis/url.h
> +  std::optional<Auth> auth_;
fixed.

2022-11-15 09:36 UTC, zhuzilin commented on torchrec/csrc/dynamic_embedding/details/redis/url.h
> +struct Auth {
fixed.

2022-11-15 09:36 UTC, zhuzilin commented on torchrec/csrc/dynamic_embedding/details/redis/url.h
> +struct ErrorCollector {
I've removed the `lexy` and written a naive manual parser.

2022-11-15 09:44 UTC, zhuzilin commented on torchrec/csrc/dynamic_embedding/details/io_parameter.h
> +struct IOPullParameter {
fixed. I've updated all appearence of "pull" into "fetch".

2022-11-15 16:04 UTC, divchenko approved these changes

2022-11-15 18:21 UTC, colin2328 approved these changes
Thanks @zhuzilin

2022-11-17 22:11 UTC, closed without merging